### ISSUE TITLE
Java Port?

### ISSUE THREAD

**Issue by sdsalyer** [skizzerz/DiceRoller#16]
Hello!  Apologies to create an issue for this question, but wasn't sure how else to get in contact.

I am curious if you are aware of any Java implementations or work-in-progress of your DiceRoller library? I was a dotnet man, which was how I initially found your library, but a career shift put me in the Java camp, so I am switching gears on personal projects as well and could use a Java version of this!

I haven't put much thought into converting it myself yet, but I'm sure the ANTLR grammar and a good chunk of the code would transfer over without much fuss, but I'm sure the devil is in the details (and in the dependencies).

Thanks!

**Comment by skizzerz** [comment]
I have no plans to make a Java port. You are welcome to make your own, however please follow the terms of the license when doing so (basically, you need to keep my name in the copyright notice. you can add your own there as well if you'd like)

**Comment by sdsalyer** [comment]
Thanks for letting me know! I just wanted to check in the case of redundant efforts when my web searches for a port of this particular code came up empty.

If I go down that road, I will first examine the license and give full attribution - - and of course let you know about it. :-)

Excellent work on this, btw, it's the best example I've come across!
