### ISSUE TITLE
Dice expression for 1D6 where 6 -> 2 successes, 3 or 4 -> 1 success?

### ISSUE THREAD

**Issue by skeolan** [skizzerz/DiceRoller#2]
Greetings! This dice roller library looks amazingly versatile, so I suspect the reason I can't figure out how to compose the expression I want is due to my own shortcomings rather than the library itself.

I'm trying to build an autoresolver for the Full Thrust tabletop game, in which (for example) beam weapons fire is resolved as follows: would you be able to describe what the dice expression should be for this? E.g. `4D6 > 3` does the job of counting successes for 4 / 5 correctly, but doesn't double-count the 6s as necessary. 

I'm contemplating coding in a For loop over the result list and adding an extra success to the total for each 6, but I'd love to know if the library itself can handle this in some way I don't see yet?

Thanks in advance!

Citation from Full Thrust Continuum, p.29 Section 4.5 "Beam Fire":
```
For every die rolled, damage is inflicted on an unscreened target ship as follows:
• Every 1, 2, or 3 rolled = no effect. (A miss or insignificant surface damage).
• Every 4 or 5 rolled = 1 damage point to the target.
• Every 6 rolled = 2 damage points to the target.
```
https://emeraldcoastskunkworks.files.wordpress.com/2014/12/full-thrust-project-continuum-version-1-1-1-april-2015.pdf

**Comment by skizzerz** [comment]
As a really hacky workaround, you could do `4d6=6f<4 + 4` or equivalently `4d6.success(=6).failure(<4) + 4`

This rolls 4d6, subtracts 1 success if the result is 1, 2, or 3 and adds 1 success if the result is 6. Then, adding 4 means you essentially add 1 success to each result (meaning 1, 2 or 3 net 0 success, 4 or 5 nets 1 success, and 6 nets 2 successes). The amount you add at the end must match the number of dice you're rolling.

I'd recommend creating a custom function instead, see the documentation and example at https://skizzerz.net/DiceRoller/Dice/DiceFunctionAttribute

Let's say you name your function "beamDamage", then you could roll `4d6.beamDamage()` and your function would then implement that logic to return numbers of successes. Let me know if you need any more help if you decide to go that route.

**Comment by skeolan** [comment]
Cool, thanks! I may take you up on that -- custom functions do sound like
the way to go, in terms of supporting this ruleset.

**Comment by skizzerz** [comment]
Going to close this issue for now since there's no work library-wise that needs to be done. If/when you want help, you can reopen this issue asking whatever you need.
