### ISSUE TITLE
Link to Documentation is Broken

### ISSUE THREAD

**Issue by prbarcelon** [skizzerz/DiceRoller#7]
The link to the documentation is broken. I've found a few cached pages on Google, but would like the old documentation, if still available, to be posted here on GitHub as well.

**Changelog**
https://webcache.googleusercontent.com/search?q=cache:ivWBFptmnmYJ:https://skizzerz.net/DiceRoller/Changelog+&cd=3&hl=en&ct=clnk&gl=us

**Documentation Page**
http://webcache.googleusercontent.com/search?q=cache:https://skizzerz.net/DiceRoller/DiceRoller

**Comment by skizzerz** [comment]
Sorry about that! The documentation site is now back online.

**Comment by prbarcelon** [comment]
Awesome, thank you!
