### ISSUE TITLE
Alter Function Timing of explosion  when used with the keephighest 

### ISSUE THREAD

**Issue by Hammzer** [skizzerz/DiceRoller#8]
Hello! I am really loving this library. It is making my dice roller so much more robust.

I am having a bit of an issue when I use .explode() with .keephighest()

` 2d10.keephighest(1).explode(>9)
Result = 10 +8* +6* = 10
`
What I am trying to get is

` 2d10.keephighest(1).explode(>9)
Result = 10 +8 +6* = 18
`

The exploded dice is being lumped in to the keephighest(1). Is there anyway to make it so that the highest is kept first, then the exploded dice is added?

**Comment by skizzerz** [comment]
You want to use .compound() instead of .explode(). Compound adds the exploding dice to the original roll, explode creates new dice for the explosions.

**Comment by Hammzer** [comment]
Thank you for the response. I'm having some trouble with the . compound command. Are there any example uses listed? I tried passing it 
`
1d15.compound(>9)
`
 But it's not triggering.

**Comment by Hammzer** [comment]
Never mind, I was in error, it was working just fine.

**Comment by skizzerz** [comment]
Glad to hear you got it working! If that solves your issue please close out this issue.

**Comment by Hammzer** [comment]
Will do, but I have a related follow up. Is there any way to alter the dice that gets exploded/compounded and or limit the number of times it can occured?

Example if I compounded 1 d10 and I wanted to have the extra dice be 1d5, or 1d10 and compound on 10 but only once even if the second dice rolls 10?

**Comment by skizzerz** [comment]
There is not a way to do that built into the roller, you'd need to add your own custom function for that (see the DiceFunctionAttribute documentation for a contrived example of how to do this). What system has mechanics like this, out of curiosity? I haven't really heard anything like that before (where you limit the number of times you explode).

**Comment by Hammzer** [comment]
In most Warhammer 40k systems when you roll 10 on a damage die you roll a 1d5 and compare the roll to a critical results table with various effects. You only roll 1 die.

**Comment by skizzerz** [comment]
I see. What I'd usually recommend is to do two separate rolls. You'd inspect the results of the first roll for "criticals" (or just results of 10), and then do a separate d5 if you find any.

That said, you can definitely do it all in one roll with a custom function.

**Comment by Hammzer** [comment]
Thank you for your help :) I will close the issue now
